#pragma config(Sensor, S1,     touch,          sensorTouch)
#pragma config(Sensor, S2,     light,          sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1)
	{
	while(SensorValue(light) < 45)
	{
		motor[motorB] = 50;
		motor[motorC] = 0;
	}

	while(SensorValue(light) > 45)
	{
		motor[motorB] = 0;
		motor[motorC] = 50;
	}
}
}
